<?xml version="1.0"?>
<robot name="excavator" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="itom" value="0.0254" /> <!-- Inches to meters conversion -->
  <xacro:property name="base_width" value="${29*itom}"/>
  <xacro:property name="base_length" value="${58*itom}"/> <!-- Max val: 50" bare minimum -->
  <xacro:property name="base_height" value="${2*itom}"/> <!-- BS'd this number, total random guess -->
  <xacro:property name="wheel_radius" value="${6*itom}"/>
  <xacro:property name="wheel_width" value="${6*itom}"/>

  <xacro:include filename="$(find exc_description)/urdf/exc.gazebo" />

  <!-- A macro for creating a wheel with a link, joint, and transmission -->
  <xacro:macro name="wheel" params="name fb lr">
    <link name="${name}">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}" />
        </geometry>
        <origin rpy="${pi/2} 0 0" />
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}" />
        </geometry>
        <origin rpy="${pi/2} 0 0" />
      </collision>
      <inertial>
        <origin xyz="0 ${wheel_width/2} 0" rpy="0 0 0"/>
        <mass value="500"/> <!-- TODO: Update with proper mass, possibly calculated from Solidworks? -->
        <inertia ixx="10.0" ixy="0.0" ixz="0.0" iyy="10.0" iyz="0.0" izz="10.0"/> <!-- TODO: Update with proper inertial values, possibly calculated from Solidworks? -->
      </inertial>
    </link>
    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}"/><!--rpy="0 0 ${pi/2}"-->
      <!-- TODO: Settle to more reasonable numbers -->
      <origin xyz="${fb*base_length/2 - 16*fb*itom} ${lr*base_width/2 + lr*wheel_width/2} ${-base_height/2}"/>
      <axis xyz="0 1 0"/>
      <limit effort="100.0"  velocity="100.0"/>
      <dynamics damping="0.7"/>
    </joint>
    <transmission name="${name}_tran">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${name}_joint">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="${name}_motor">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
        <motorTorqueConstant>1</motorTorqueConstant>
      </actuator>
    </transmission>
  </xacro:macro>

  <link name="tread_left" >
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="${base_length/2-wheel_radius} 0 ${-wheel_width/2}" />
    </visual>
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="${-base_length/2+wheel_radius} 0 ${-wheel_width/2}" />
    </visual>
    <visual>
      <geometry>
        <box size="${base_length-2*wheel_radius} ${2*wheel_radius} ${wheel_width}" />
      </geometry>
      <origin xyz="0 0 ${-wheel_width/2}" />
    </visual>
  </link>

  <link name="tread_right" >
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="${base_length/2-wheel_radius} 0 ${wheel_width/2}" />
    </visual>
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="${-base_length/2+wheel_radius} 0 ${wheel_width/2}" />
    </visual>
    <visual>
      <geometry>
        <box size="${base_length-2*wheel_radius} ${2*wheel_radius} ${wheel_width}" />
      </geometry>
      <origin xyz="0 0 ${wheel_width/2}" />
    </visual>
  </link>

  <joint name="left_tread_to_base" type="fixed">
    <parent link="base_link" />
    <child link="tread_left" />
    <origin xyz="0 ${base_width/2} ${-base_height/2}" rpy="${pi/2} 0 0" />
  </joint>
    <joint name="right_tread_to_base" type="fixed">
      <parent link="base_link" />
      <child link="tread_right" />
      <origin xyz="0 ${-base_width/2} ${-base_height/2}" rpy="${pi/2} 0 0" />
    </joint>

  <link name="god" /> <!-- This is necessary because Gazebo complains about the base link having inertia, for some reason -->
  <link name="base_link" >
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}" />
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}" />
      </geometry>
    </collision>
    <inertial>
      <mass value="50"/> <!-- TODO: Update with proper mass, possibly calculated from Solidworks? -->
      <inertia ixx="100.0" ixy="0.0" ixz="0.0" iyy="100.0" iyz="0.0" izz="100.0"/> <!-- TODO: Update with proper inertial values, possibly calculated from Solidworks? -->
    </inertial>
  </link>

  <xacro:wheel name="wheel_fr" fb="1" lr="-1" />
  <xacro:wheel name="wheel_fl" fb="1" lr="1" />
  <xacro:wheel name="wheel_rr" fb="-1" lr="-1" />
  <xacro:wheel name="wheel_rl" fb="-1" lr="1" />

  <joint name="god_to_base" type="fixed">
    <parent link="god" />
    <child link="base_link" />
    <origin xyz="0 0 0" />
  </joint>


 <joint name="imu_joint" type="fixed">
      <axis xyz="0 0 0"/>
      <origin xyz="0 0 0.0512"/>
      <parent link="base_link"/>
      <child link="imu_link"/>
  </joint>
  <link name="imu_link">
      <inertial>
          <mass value="0.05"/>
          <origin rpy="0 0 0" xyz="0 0 .05"/>
          <inertia ixx="0.05" ixy="0" ixz="0" iyy="0.05" iyz="0" izz="0.05"/>
      </inertial>
      <visual>
          <origin rpy="0 0 0" xyz="0 0 0.05"/>
          <geometry>
              <box size="0.1 0.1 0.1"/>
          </geometry>
      </visual>
      <collision>
          <origin rpy="0 0 0" xyz="0 0 .05"/>
          <geometry>
              <box size=".1 .1 .1"/>
          </geometry>
      </collision>
  </link>

  <gazebo>
      <plugin name="imu_plugin" filename="libgazebo_ros_imu.so">
          <robotNamespace>/exc</robotNamespace>
          <alwaysOn>true</alwaysOn>
          <xyzOffset>0 0 .05</xyzOffset>
          <bodyName>imu_link</bodyName>
          <topicName>imu</topicName>
          <serviceName>imu_service</serviceName>
          <frameName>imu_link</frameName>
          <gaussianNoise>0.00</gaussianNoise>
          <updateRate>20.0</updateRate>
      </plugin>
</gazebo>

<!--  <gazebo reference="imu_link">
    <gravity>true</gravity>
   <sensor name="imu_sensor" type="imu">
      <always_on>true</always_on>
      <update_rate>50</update_rate>
      <visualize>true</visualize>
      <topic>imuTest</topic>
      <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
        <robotNamespace>/exc</robotNamespace>
        <topicName>imu</topicName>
        <bodyName>imu_link</bodyName>
        <updateRateHZ>50.0</updateRateHZ>
        <gaussianNoise>0.00</gaussianNoise>
        <xyzOffset>0 0 0.05</xyzOffset>
        <rpyOffset>0 0 0</rpyOffset>
        <frameName>imu_link</frameName>
      </plugin>
      <pose>0 0 0 0 0 0</pose>
    </sensor>
</gazebo>-->

</robot>
