<?xml version="1.0"?>
<robot name="excavator" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="itom" value="0.0254" /> <!-- Inches to meters conversion -->

  <xacro:property name="base_width" value="${29*itom}"/>
  <xacro:property name="base_length" value="${58*itom}"/> <!-- Max val: 50" bare minimum -->
  <xacro:property name="base_height" value="${2*itom}"/> <!-- BS'd this number, total random guess -->
  <xacro:property name="wheel_radius" value="${6*itom}"/>
  <xacro:property name="wheel_width" value="${6*itom}"/>

  <xacro:include filename="$(find exc_description)/urdf/exc.gazebo" />

  <!-- fold Base Robot -->

  <!-- A macro for creating a wheel with a link, joint, and transmission -->
  <xacro:macro name="wheel" params="name fb lr">
    <link name="${name}">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}" />
        </geometry>
        <origin rpy="${pi/2} 0 0" />
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}" />
        </geometry>
        <origin rpy="${pi/2} 0 0" />
      </collision>
      <inertial>
        <origin xyz="0 ${wheel_width/2} 0" rpy="0 0 0"/>
        <mass value="500"/> <!-- TODO: Update with proper mass, possibly calculated from Solidworks? -->
        <inertia ixx="10.0" ixy="0.0" ixz="0.0" iyy="10.0" iyz="0.0" izz="10.0"/> <!-- TODO: Update with proper inertial values, possibly calculated from Solidworks? -->
      </inertial>
    </link>
    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}"/><!--rpy="0 0 ${pi/2}"-->
      <!-- TODO: Settle to more reasonable numbers -->
      <origin xyz="${fb*base_length/2 - 16*fb*itom} ${lr*base_width/2 + lr*wheel_width/2} ${-base_height/2}"/>
      <axis xyz="0 1 0"/>
      <limit effort="100.0"  velocity="100.0"/>
      <dynamics damping="0.7"/>
    </joint>
    <transmission name="${name}_tran">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${name}_joint">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="${name}_motor">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
        <motorTorqueConstant>1</motorTorqueConstant>
      </actuator>
    </transmission>
  </xacro:macro>

  <link name="tread_left" >
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="${base_length/2-wheel_radius} 0 ${-wheel_width/2}" />
    </visual>
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="${-base_length/2+wheel_radius} 0 ${-wheel_width/2}" />
    </visual>
    <visual>
      <geometry>
        <box size="${base_length-2*wheel_radius} ${2*wheel_radius} ${wheel_width}" />
      </geometry>
      <origin xyz="0 0 ${-wheel_width/2}" />
    </visual>
  </link>

  <link name="tread_right" >
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="${base_length/2-wheel_radius} 0 ${wheel_width/2}" />
    </visual>
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="${-base_length/2+wheel_radius} 0 ${wheel_width/2}" />
    </visual>
    <visual>
      <geometry>
        <box size="${base_length-2*wheel_radius} ${2*wheel_radius} ${wheel_width}" />
      </geometry>
      <origin xyz="0 0 ${wheel_width/2}" />
    </visual>
  </link>

  <joint name="left_tread_to_base" type="fixed">
    <parent link="base_link" />
    <child link="tread_left" />
    <origin xyz="0 ${base_width/2} ${-base_height/2}" rpy="${pi/2} 0 0" />
  </joint>
  <joint name="right_tread_to_base" type="fixed">
    <parent link="base_link" />
    <child link="tread_right" />
    <origin xyz="0 ${-base_width/2} ${-base_height/2}" rpy="${pi/2} 0 0" />
  </joint>

  <link name="god" /> <!-- This is necessary because Gazebo complains about the base link having inertia, for some reason -->
  <link name="base_link" >
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}" />
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}" />
      </geometry>
    </collision>
    <inertial>
      <mass value="50"/> <!-- TODO: Update with proper mass, possibly calculated from Solidworks? -->
      <inertia ixx="100.0" ixy="0.0" ixz="0.0" iyy="100.0" iyz="0.0" izz="100.0"/> <!-- TODO: Update with proper inertial values, possibly calculated from Solidworks? -->
    </inertial>
  </link>

  <xacro:wheel name="wheel_fr" fb="1" lr="-1" />
  <xacro:wheel name="wheel_fl" fb="1" lr="1" />
  <xacro:wheel name="wheel_rr" fb="-1" lr="-1" />
  <xacro:wheel name="wheel_rl" fb="-1" lr="1" />

  <joint name="god_to_base" type="fixed">
    <parent link="god" />
    <child link="base_link" />
    <origin xyz="0 0 0" />
  </joint>

  <!-- /fold -->

  <!-- fold Turntable -->
  <link name="turntable">
    <visual>
      <geometry>
        <cylinder radius="${base_width/3}" length="${6*itom}" />
      </geometry>
      <origin xyz="0 0 ${3*itom}" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${base_width/3}" length="${6*itom}" />
        <origin xyz="0 0 ${3*itom}" />
      </geometry>
    </collision>
    <inertial>
      <mass value="50"/> <!-- TODO: Update with proper mass, possibly calculated from Solidworks? -->
      <inertia ixx="100.0" ixy="0.0" ixz="0.0" iyy="100.0" iyz="0.0" izz="100.0"/> <!-- TODO: Update with proper inertial values, possibly calculated from Solidworks? -->
    </inertial>
  </link>

  <joint name="turn_to_base" type="continuous">
    <parent link="base_link" />
    <child link="turntable" />
    <origin xyz="${base_length/2-base_width/3-3*itom} 0 ${base_height/2}" />
    <axis xyz="0 0 1" />
    <limit effort="10000.0"  velocity="0.25"/>
    <dynamics damping="0.7"/>
  </joint>
  <transmission name="turntable_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="turn_to_base">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="turntable_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
      <motorTorqueConstant>1</motorTorqueConstant>
    </actuator>
  </transmission>
  <!-- /fold -->

  <link name="arm_lower">
    <visual>
      <geometry>
        <box size="${4*itom} ${4*itom} ${36*itom}" />
      </geometry>
      <origin xyz="0 0 ${18*itom}" />
    </visual>
    <collision>
      <geometry>
        <box size="${4*itom} ${4*itom} ${36*itom}" />
      </geometry>
      <origin xyz="0 0 ${18*itom}" />
    </collision>
    <inertial>
      <mass value="50"/> <!-- TODO: Update with proper mass, possibly calculated from Solidworks? -->
      <inertia ixx="100.0" ixy="0.0" ixz="0.0" iyy="100.0" iyz="0.0" izz="100.0"/> <!-- TODO: Update with proper inertial values, possibly calculated from Solidworks? -->
    </inertial>
  </link>
  <joint name="lower_to_turn" type="revolute">
    <parent link="turntable" />
    <child link="arm_lower" />
    <axis xyz="0 1 0" />
    <origin xyz="0 0 ${6*itom}" />
    <limit effort="10000.0"  velocity="0.25" lower="${-pi/6}" upper="${3*pi/8}"/>
    <dynamics damping="5.0"/>
  </joint>
  <transmission name="lower_arm_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="lower_to_turn">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="lower_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
      <motorTorqueConstant>1</motorTorqueConstant>
    </actuator>
  </transmission>


  <link name="arm_upper">
    <visual>
      <geometry>
        <box size="${4*itom} ${4*itom} ${36*itom}" />
      </geometry>
      <origin xyz="0 0 ${18*itom}" />
    </visual>
    <collision>
      <geometry>
        <box size="${4*itom} ${4*itom} ${36*itom}" />
      </geometry>
      <origin xyz="0 0 ${18*itom}" />
    </collision>
    <inertial>
      <mass value="50"/> <!-- TODO: Update with proper mass, possibly calculated from Solidworks? -->
      <inertia ixx="100.0" ixy="0.0" ixz="0.0" iyy="100.0" iyz="0.0" izz="100.0"/> <!-- TODO: Update with proper inertial values, possibly calculated from Solidworks? -->
    </inertial>
  </link>
  <joint name="upper_to_lower" type="revolute">
    <parent link="arm_lower" />
    <child link="arm_upper" />
    <axis xyz="0 1 0" />
    <origin xyz="0 0 ${36*itom}" />
    <limit effort="10000.0"  velocity="0.25" lower="0.0" upper="${3*pi/8}"/>
    <dynamics damping="5.0"/>
  </joint>
  <transmission name="upper_arm_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="upper_to_lower">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="upper_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
      <motorTorqueConstant>1</motorTorqueConstant>
    </actuator>
  </transmission>

  <link name="arm_end" >
    <visual>
      <geometry>
        <box size="${12*itom} ${12*itom} ${4*itom}" />
      </geometry>
      <origin xyz="${6*itom} 0 0" />
    </visual>
    <inertial>
      <mass value="50"/> <!-- TODO: Update with proper mass, possibly calculated from Solidworks? -->
      <inertia ixx="100.0" ixy="0.0" ixz="0.0" iyy="100.0" iyz="0.0" izz="100.0"/> <!-- TODO: Update with proper inertial values, possibly calculated from Solidworks? -->
    </inertial>
  </link>
  <joint name="end_to_arm" type="revolute">
    <parent link="arm_upper" />
    <child link="arm_end" />
    <origin xyz="0 0 ${36*itom}" />
    <axis xyz="0 1 0" />
    <limit effort="10000.0" velocity="0.25" lower="${-3*pi/8}" upper="${pi/4}" />
    <dynamics damping="5.0"/>
  </joint>
  <transmission name="arm_end_tran">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="end_to_arm">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="end_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
      <motorTorqueConstant>1</motorTorqueConstant>
    </actuator>
  </transmission>
</robot>
