scan_filter_chain:
- name: all_inside_bot
  type: LaserScanBoxFilter
  params:
    box_frame: base_link
    min_x: -0.9
    max_x: 0.9
    min_y: -0.5334
    max_y: 0.5334
    min_z: -1.0
    max_z: 1.0
